### PR TITLE
Fix issues with Clang

### PR DESCRIPTION
**Pull request by ConiKost**
This should fix everything from https://github.com/M-Reimer/graphlcd-base/issues/4.
Works for me locally with GCC and Clang.

### CODE REVIEW

**Comment by M-Reimer** [comment]
Thank you very much.

I wonder if there is any way to keep the .c files. As mentioned clang is not top priority and the project was not initially developed by me. If I had set that up, I had used .cpp file extensions for sure.

I occasionally have to browse through the commit history or use "git blame" to understand code better. I'm still learning about some parts how they are working. Renaming every single .c file creates a cut in history and will be a pain in the future when trying to analyze code.

Is clang really that dependent on file extensions that it won't work with other extensions at all?

**Comment by ConiKost** [comment]
> I wonder if there is any way to keep the .c files. As mentioned clang is not top priority and the project was not initially developed by me. If I had set that up, I had used .cpp file extensions for sure.

I don't think, there is a way out. Clang explict warns about, that using .c for cpp is deprecated and will be removed in future. I am not sure about GCC.

> Renaming every single .c file creates a cut in history and will be a pain in the future when trying to analyze code.

Are you sure? Since files have been moved with ```git mv```, history should be taken over?

> Is clang really that dependent on file extensions that it won't work with other extensions at all?

Currently, it still works, but it already warns about it. ```warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]```. So you can bet, that this will be removed in future.

**Comment by M-Reimer** [comment]
Thanks again for your support. I have created a small test repo to check how GitHub handles file moves:
https://github.com/M-Reimer/test_move_file/blame/master/test.lst
https://github.com/M-Reimer/test_move_file/commits/master/test.lst
And this seems to be OK for me.

The main reason why all the files are ".c" files may be that the project initially was meant to be used with VDR only and so it took some design decisions made in VDR. Among those is the "we use .c files for C++ code". But there is no real reason to keep it that way.

**Comment by eli-schwartz** [comment]
Git tries to detect renames and handle them gracefully, and GitHub also tries to wrap that in its web UI.

For the command line tools, you may need to use e.g. `git log -p --follow foo.cpp` to follow renames.

**Comment by ConiKost** [comment]
Thank you! :-)

**Pull request merged**
